#!/usr/bin/env ruby
# tools/img2rle.rb — Convert an image to RLE-encoded RGB565 Ruby data for prremote LCD.
#
# Output format: packed binary string constant (4 bytes/segment).
#   Bytes 0-1: RGB565 color, big-endian
#   Bytes 2-3: pixel count, big-endian (row-bounded; max = LCD width)
#
# Decoding on device uses String#getbyte — see draw_face_b in shoku.rb.
# Bytecode size: ~4 bytes/segment (vs ~18 bytes for a Ruby array), so typical
# cartoon images (2000-6000 segments) fit within the 64 KB mrb buffer.
#
# Usage:
#   ruby tools/img2rle.rb INPUT [OUTPUT] [options]
#
# Options:
#   -w, --width W    Target width  (default: 320)
#   -h, --height H   Target height (default: 240)
#   -c, --const NAME Ruby constant name (default: derived from INPUT filename)
#
# Requires ImageMagick (brew install imagemagick).
#
# Workflow:
#   ruby tools/img2rle.rb bai.png samples/esp32/bai_rle.rb
#   prremote run samples/esp32/bai_rle.rb samples/esp32/shoku.rb

require 'optparse'
require 'tempfile'

options = { width: 320, height: 240 }
OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename($PROGRAM_NAME)} INPUT [OUTPUT] [options]"
  opts.on('-w', '--width W',  Integer, 'Target width  (default: 320)') { |v| options[:width]  = v }
  opts.on('-h', '--height H', Integer, 'Target height (default: 240)') { |v| options[:height] = v }
  opts.on('-c', '--const C',  String,  'Constant name') { |v| options[:const] = v }
  opts.on_tail('--help', 'Show this help') do
    puts opts
    exit
  end
end.parse!

input = ARGV.shift or abort "Input file required. Run with --help for usage."
abort "File not found: #{input}" unless File.exist?(input)

w     = options[:width]
h     = options[:height]
const = options[:const] || "#{File.basename(input, '.*').upcase.gsub(/[^A-Z0-9]+/, '_')}_RLE"
output = ARGV.shift || File.join(File.dirname(input), "#{File.basename(input, '.*')}_rle.rb")

# Prefer "magick" (IMv7+); fall back to "convert" (IMv4/5/6).
magick_cmd = if system('magick', '--version', out: IO::NULL, err: IO::NULL)
               'magick'
             elsif system('convert', '--version', out: IO::NULL, err: IO::NULL)
               'convert'
             else
               abort 'ImageMagick not found. Install with: brew install imagemagick'
             end

# Resize and export as raw RGB888 (3 bytes/pixel, no header) via temp file.
# -background white -flatten handles transparency (e.g. PNG with alpha).
warn "Converting #{File.basename(input)} → #{w}x#{h} RGB565..."
tmp = Tempfile.new(['img2rle', '.rgb'])
tmp_path = tmp.path
tmp.close
begin
  ok = system(magick_cmd, input,
              '-background', 'white', '-flatten',
              '-resize', "#{w}x#{h}!",
              '-type', 'TrueColor',
              '-depth', '8',
              "rgb:#{tmp_path}")
  abort 'ImageMagick convert failed' unless ok

  raw = File.binread(tmp_path)
ensure
  File.unlink(tmp_path) rescue nil
end

expected = w * h * 3
abort "Unexpected output size #{raw.bytesize} (expected #{expected})" unless raw.bytesize == expected

# RLE-encode row by row.
# Flushing at each row boundary keeps each segment within a single scanline,
# so draw_face_b can render it as fill_rect(x, y, count, 1, color).
warn 'RLE encoding...'
rle = []
(0...h).each do |row|
  run_color = nil
  run_count = 0
  (0...w).each do |col|
    base = ((row * w) + col) * 3
    r, g, b = raw.getbyte(base), raw.getbyte(base + 1), raw.getbyte(base + 2)
    color = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    if color == run_color
      run_count += 1
    else
      rle << [run_color, run_count] if run_color
      run_color = color
      run_count = 1
    end
  end
  rle << [run_color, run_count] if run_color # flush at row boundary
end

segments  = rle.size
ratio     = (w.to_f * h / segments).round(1)
bin_bytes = segments * 4
mrb_est   = bin_bytes + 4096 # rough estimate: string pool + shokupanman overhead

warn "RLE: #{segments} segments, #{ratio}x compression → #{bin_bytes} bytes packed"
if mrb_est > 64 * 1024
  warn "WARNING: estimated mrb size ~#{mrb_est / 1024}KB may exceed 64KB buffer."
  warn "  Try posterizing the image first: #{magick_cmd} input.jpg -posterize 6 output.jpg"
end

# Build packed binary string: each segment = 4 bytes (color hi, color lo, count hi, count lo).
# Adjacent string literals joined by backslash line-continuation (Ruby parse-time concat).
# 16 segments per source line (64 bytes of escaped data) for readability.
SEGS_PER_LINE = 16

File.open(output, 'w') do |f|
  f.puts "# Generated by tools/img2rle.rb"
  f.puts "# Source : #{File.basename(input)}  →  #{w}x#{h} px, RGB565 RLE (packed binary)"
  f.puts "# Segments: #{segments} (#{ratio}x compression), packed #{bin_bytes} bytes"
  f.puts "# Usage  : prremote run #{File.basename(output)} samples/esp32/shoku.rb"
  f.puts "# Format : 4 bytes/segment — color (big-endian u16), count (big-endian u16)"

  slices = rle.each_slice(SEGS_PER_LINE).to_a
  slices.each_with_index do |slice, idx|
    hex = slice.flat_map do |color, count|
      [(color >> 8) & 0xFF, color & 0xFF, (count >> 8) & 0xFF, count & 0xFF]
    end.map { |b| "\\x#{b.to_s(16).rjust(2, '0')}" }.join
    continuation = idx < slices.size - 1 ? ' \\' : ''
    prefix = idx == 0 ? "#{const} = \"" : '  "'
    f.puts "#{prefix}#{hex}\"#{continuation}"
  end
end

warn "Written: #{output}  (#{File.size(output)} bytes source)"
