AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 120
