AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "wk/**/*"
    - "runtime/**/*"
    - "pkg/**/*"

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 600

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 130

Style/NumericPredicate:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/NumericLiterals:
  Enabled: false
